<a href="https://colab.research.google.com/github/SophieShin/DeepLearning/blob/main/%5BSSH%5Dlab02b_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2b – Tensors

In [1]:
import torch

## Create empty tensors
- Uninitialised tensors

In [2]:
x = torch.empty(1)
x

tensor([14045.7500])

In [3]:
x = torch.empty(2)
print(x)
print(f'1-D tensor{x}')

tensor([1.4046e+04, 3.0742e-41])
1-D tensortensor([1.4046e+04, 3.0742e-41])


In [4]:
x = torch.empty(2)
print(x)
print(f"\n1-D tensor\n{x}\n")

tensor([1.4046e+04, 3.0742e-41])

1-D tensor
tensor([1.4046e+04, 3.0742e-41])



In [5]:
x= torch.empty(2,3)
print(x)

print(f"2-D tensor\n{x}\n")

tensor([[1.4046e+04, 3.0742e-41, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])
2-D tensor
tensor([[1.4046e+04, 3.0742e-41, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])



In [6]:
x = torch.empty(2,3,1)
print(x)

tensor([[[1.4046e+04],
         [3.0742e-41],
         [5.0447e-44]],

        [[0.0000e+00],
         [       nan],
         [0.0000e+00]]])


In [7]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([14046.2500])

1-D tensor
tensor([1.4046e+04, 3.0742e-41])

2-D tensor
tensor([[1.4046e+04, 3.0742e-41, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

3-D tensor
 tensor([[[1.4046e+04],
         [3.0742e-41],
         [5.0447e-44]],

        [[0.0000e+00],
         [       nan],
         [0.0000e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [8]:
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# scalar인 경우에는  []를 쓰지 않는다
# torch.Size([])로 표현된다(0차원이라는 뜻)

Scalar: 3 has shape torch.Size([]) and 0 dimensions



In [9]:
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)
print(x.shape)

Random values:
tensor([[0.5887, 0.9449, 0.4531],
        [0.3582, 0.6151, 0.5076]])
torch.float32
torch.Size([2, 3])


In [10]:
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)


Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [12]:
x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")



Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [13]:
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")
print(x)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
x = torch.ones(2,3, dtype=torch.double) #torch.double은 float64를 의미. 기본은 float32
print(f"Ones:\n{x}")

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

Scalar: 3 has shape torch.Size([]) and 0 dimensions



In [ ]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.2386, 0.1133, 0.4724],
        [0.7101, 0.8022, 0.0432]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [16]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)
print(x.dtype)

tensor([0.5000, 2.7000])
torch.float32


### Changing tensor data type


In [17]:
x = torch.rand(2,3)
x

tensor([[0.7670, 0.1996, 0.5613],
        [0.5686, 0.6774, 0.7897]])

In [18]:
x*20

tensor([[15.3401,  3.9923, 11.2259],
        [11.3716, 13.5487, 15.7936]])

In [19]:
y = x.to(torch.int32) # 간단하게 x.to(바꿀타입)으로 하면 됨
print(y)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [20]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[10.3654,  3.7738, 13.4046],
        [18.9772, 19.9274, 18.3959]])
tensor([[10,  3, 13],
        [18, 19, 18]], dtype=torch.int32)


### Create a separate copy



In [21]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [22]:
b = a.clone() # numpy의 copy랑 비슷!
b

tensor([[1., 1.],
        [1., 1.]])

In [23]:
c= a.copy() # copy function은 안되고 clone으로 해야됨
c

AttributeError: ignored

In [25]:
a[0][1] = 561
print(a)
print(b) # b는 a를 가리키고 있는게 아니고 별개의 copy/clone을 만든 것이므로 a를 변경해도 b는 영향을 받지 않는다.

tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[1., 1.],
        [1., 1.]])


In [26]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [27]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.9592, 0.7378],
        [0.8525, 0.3566]])

y = 
tensor([[0.6207, 0.5823],
        [0.5331, 0.4858]])

x + y = 
tensor([[1.5799, 1.3201],
        [1.3855, 0.8424]])
x - y = 
tensor([[ 0.3385,  0.1556],
        [ 0.3194, -0.1292]])
x * y = 
tensor([[0.5953, 0.4296],
        [0.4544, 0.1732]])
x / y = 
tensor([[1.5454, 1.2672],
        [1.5992, 0.7341]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [28]:
# 이렇게 하면 위의 결과와 달리 y 값이 바뀐다는것!!

x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.8344, 0.9839],
        [0.8017, 0.0533]])

y = 
tensor([[0.7538, 0.7146],
        [0.5836, 0.9747]])

y + x = tensor([[1.5882, 1.6985],
        [1.3854, 1.0280]])
y - x = tensor([[0.7538, 0.7146],
        [0.5836, 0.9747]])
y * x = tensor([[0.6289, 0.7031],
        [0.4679, 0.0520]])
y / x = tensor([[0.7538, 0.7146],
        [0.5836, 0.9747]])


## Accessing tensors

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
# 이 경우에는 tensor로 표현이 안됨
# data type이 어떻게 달라지는건지?
print(x[2,2].item())


y = torch.tensor([2.0])
print(y.item())

tensor([[0.4472, 0.5956, 0.1357],
        [0.7330, 0.3692, 0.4429],
        [0.5104, 0.5344, 0.9710],
        [0.8358, 0.2809, 0.1880],
        [0.8678, 0.5615, 0.5915]])
tensor([0.4472, 0.7330, 0.5104, 0.8358, 0.8678])
tensor([0.7330, 0.3692, 0.4429])
tensor(0.9710)
0.9710344076156616
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [36]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.9087, 0.6912, 0.0228],
        [0.9275, 0.7184, 0.4499],
        [0.4989, 0.0556, 0.2944],
        [0.6629, 0.6873, 0.2757],
        [0.9535, 0.5490, 0.8192]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [37]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')
# column-wise

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')
# row-wise


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``
- the number of elements should be same


In [39]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

Original:
tensor([[0.3215, 0.6616, 0.8614, 0.7058],
        [0.7694, 0.6489, 0.2028, 0.9677],
        [0.4560, 0.9048, 0.7932, 0.8094],
        [0.9760, 0.0124, 0.5274, 0.1713]])
torch.Size([4, 4])


In [40]:
# Reshape (flatten) to 1-D(implicitly mean)
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

Reshaped to 1-D:
tensor([0.3215, 0.6616, 0.8614, 0.7058, 0.7694, 0.6489, 0.2028, 0.9677, 0.4560,
        0.9048, 0.7932, 0.8094, 0.9760, 0.0124, 0.5274, 0.1713])


In [42]:
# Reshape to 2-D # 순서는 첫째 row 읽고, 둘째 row 읽고 이런 식으로
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

Reshaped to 2-D:
tensor([[0.3215, 0.6616],
        [0.8614, 0.7058],
        [0.7694, 0.6489],
        [0.2028, 0.9677],
        [0.4560, 0.9048],
        [0.7932, 0.8094],
        [0.9760, 0.0124],
        [0.5274, 0.1713]])


In [43]:
y = x.reshape(8, -1)
print(y)

tensor([[0.3215, 0.6616],
        [0.8614, 0.7058],
        [0.7694, 0.6489],
        [0.2028, 0.9677],
        [0.4560, 0.9048],
        [0.7932, 0.8094],
        [0.9760, 0.0124],
        [0.5274, 0.1713]])


In [44]:
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

Reshaped to 2 x Unspecified 2-D:
tensor([[0.3215, 0.6616, 0.8614, 0.7058, 0.7694, 0.6489, 0.2028, 0.9677],
        [0.4560, 0.9048, 0.7932, 0.8094, 0.9760, 0.0124, 0.5274, 0.1713]])
torch.Size([2, 8])


## squeeze, unsqueeze 다시 해보기
- squeeze() :  괄호 안에 안써도 됨, 1인 차원을 없애줌
- unsqueeze() : 괄호 안의 parameter는 어떤 dimension인지 나타냄. 그 위치에 1차원을 추가하는 것

In [47]:
print(x)
print(x.shape)

tensor([[0.3215, 0.6616, 0.8614, 0.7058],
        [0.7694, 0.6489, 0.2028, 0.9677],
        [0.4560, 0.9048, 0.7932, 0.8094],
        [0.9760, 0.0124, 0.5274, 0.1713]])
torch.Size([4, 4])


In [49]:
# 
y = x.unsqueeze(1)
print(y)
print(y.shape)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')


tensor([[[0.3215, 0.6616, 0.8614, 0.7058]],

        [[0.7694, 0.6489, 0.2028, 0.9677]],

        [[0.4560, 0.9048, 0.7932, 0.8094]],

        [[0.9760, 0.0124, 0.5274, 0.1713]]])
torch.Size([4, 1, 4])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([4, 1, 4])


In [52]:
y = x.unsqueeze(0)
print(y)
print(y.shape)


tensor([[[0.3215, 0.6616, 0.8614, 0.7058],
         [0.7694, 0.6489, 0.2028, 0.9677],
         [0.4560, 0.9048, 0.7932, 0.8094],
         [0.9760, 0.0124, 0.5274, 0.1713]]])
torch.Size([1, 4, 4])


In [56]:
z = torch.squeeze(x)
print(x.shape)
print(z.shape)

torch.Size([4, 4])
torch.Size([4, 4])


In [57]:
x = torch.rand(4,3,1)
x

tensor([[[2.7583e-01],
         [8.6277e-02],
         [1.7219e-01]],

        [[2.9095e-01],
         [4.4447e-01],
         [6.5969e-01]],

        [[5.1042e-01],
         [7.8735e-01],
         [1.0641e-01]],

        [[5.3445e-01],
         [7.3940e-04],
         [3.1674e-01]]])

In [58]:
z = x.squeeze()
z

tensor([[2.7583e-01, 8.6277e-02, 1.7219e-01],
        [2.9095e-01, 4.4447e-01, 6.5969e-01],
        [5.1042e-01, 7.8735e-01, 1.0641e-01],
        [5.3445e-01, 7.3940e-04, 3.1674e-01]])

In [59]:
print(x.ndim)
print(z.ndim)

3
2


In [61]:
print(x.shape)
print(z.shape)

torch.Size([4, 3, 1])
torch.Size([4, 3])


In [ ]:
  
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.6845, 0.9159, 0.0661, 0.6028],
        [0.2597, 0.6588, 0.5732, 0.2809],
        [0.5372, 0.2705, 0.6606, 0.1182],
        [0.7645, 0.1008, 0.2942, 0.6459]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.6845, 0.9159, 0.0661, 0.6028, 0.2597, 0.6588, 0.5732, 0.2809, 0.5372,
        0.2705, 0.6606, 0.1182, 0.7645, 0.1008, 0.2942, 0.6459])
Reshaped to 2-D:
tensor([[0.6845, 0.9159],
        [0.0661, 0.6028],
        [0.2597, 0.6588],
        [0.5732, 0.2809],
        [0.5372, 0.2705],
        [0.6606, 0.1182],
        [0.7645, 0.1008],
        [0.2942, 0.6459]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.6845, 0.9159, 0.0661, 0.6028, 0.2597, 0.6588, 0.5732, 0.2809],
        [0.5372, 0.2705, 0.6606, 0.1182, 0.7645, 0.1008, 0.2942, 0.6459]])
torch.Size([2, 8])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [62]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [63]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [93]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )

# Print x
x = torch.linspace(2, 200,100)
print(x)


tensor([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,
         26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,
         50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,
         74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
         98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
        122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142., 144.,
        146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166., 168.,
        170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190., 192.,
        194., 196., 198., 200.])


In [94]:
# 2. Print the first 5 numbers in x.
print(x[:5])

# 3. Print the last 5 numbers in x
print(x[-5:])

tensor([ 2.,  4.,  6.,  8., 10.])
tensor([192., 194., 196., 198., 200.])


In [95]:
# 4. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(100)
# Print y
print(y)

tensor([0.0793, 0.9924, 0.9953, 0.5343, 0.9058, 0.6955, 0.8302, 0.6304, 0.5180,
        0.4471, 0.0091, 0.3217, 0.5287, 0.4050, 0.4572, 0.5319, 0.0340, 0.7972,
        0.2932, 0.6643, 0.9251, 0.4565, 0.3749, 0.9208, 0.9309, 0.2145, 0.6194,
        0.5246, 0.7954, 0.9232, 0.5399, 0.8035, 0.1672, 0.4571, 0.4250, 0.9886,
        0.1056, 0.7105, 0.7786, 0.1278, 0.3948, 0.8539, 0.3978, 0.2838, 0.0344,
        0.0765, 0.5820, 0.4457, 0.4763, 0.8032, 0.5808, 0.8981, 0.2169, 0.7047,
        0.4531, 0.4620, 0.6838, 0.8320, 0.5999, 0.8361, 0.9356, 0.0593, 0.3750,
        0.9715, 0.5181, 0.4519, 0.2821, 0.6554, 0.1046, 0.1623, 0.8679, 0.3893,
        0.0332, 0.4045, 0.3555, 0.2440, 0.4842, 0.1589, 0.4713, 0.6301, 0.4700,
        0.9911, 0.2599, 0.5831, 0.6647, 0.1772, 0.9260, 0.3736, 0.4442, 0.4132,
        0.2806, 0.0856, 0.2347, 0.8274, 0.4096, 0.5844, 0.7283, 0.0221, 0.4833,
        0.2914])


In [96]:
# 5. Multiply x and y, store the result in z
z = torch.mul(x, y)

# Print z
print(z)


tensor([1.5851e-01, 3.9695e+00, 5.9719e+00, 4.2746e+00, 9.0581e+00, 8.3460e+00,
        1.1623e+01, 1.0086e+01, 9.3240e+00, 8.9421e+00, 2.0066e-01, 7.7218e+00,
        1.3745e+01, 1.1339e+01, 1.3717e+01, 1.7022e+01, 1.1573e+00, 2.8700e+01,
        1.1142e+01, 2.6574e+01, 3.8854e+01, 2.0087e+01, 1.7248e+01, 4.4198e+01,
        4.6544e+01, 1.1155e+01, 3.3446e+01, 2.9376e+01, 4.6131e+01, 5.5394e+01,
        3.3476e+01, 5.1422e+01, 1.1036e+01, 3.1080e+01, 2.9747e+01, 7.1180e+01,
        7.8112e+00, 5.4001e+01, 6.0734e+01, 1.0227e+01, 3.2375e+01, 7.1729e+01,
        3.4210e+01, 2.4976e+01, 3.0932e+00, 7.0406e+00, 5.4712e+01, 4.2790e+01,
        4.6682e+01, 8.0315e+01, 5.9237e+01, 9.3400e+01, 2.2987e+01, 7.6110e+01,
        4.9845e+01, 5.1739e+01, 7.7957e+01, 9.6511e+01, 7.0791e+01, 1.0034e+02,
        1.1414e+02, 7.3491e+00, 4.7253e+01, 1.2435e+02, 6.7357e+01, 5.9647e+01,
        3.7795e+01, 8.9134e+01, 1.4440e+01, 2.2720e+01, 1.2324e+02, 5.6057e+01,
        4.8459e+00, 5.9865e+01, 5.3323e+

In [97]:
# 6. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5, 20)

# Print z2
print(z2)

tensor([[1.5851e-01, 3.9695e+00, 5.9719e+00, 4.2746e+00, 9.0581e+00, 8.3460e+00,
         1.1623e+01, 1.0086e+01, 9.3240e+00, 8.9421e+00, 2.0066e-01, 7.7218e+00,
         1.3745e+01, 1.1339e+01, 1.3717e+01, 1.7022e+01, 1.1573e+00, 2.8700e+01,
         1.1142e+01, 2.6574e+01],
        [3.8854e+01, 2.0087e+01, 1.7248e+01, 4.4198e+01, 4.6544e+01, 1.1155e+01,
         3.3446e+01, 2.9376e+01, 4.6131e+01, 5.5394e+01, 3.3476e+01, 5.1422e+01,
         1.1036e+01, 3.1080e+01, 2.9747e+01, 7.1180e+01, 7.8112e+00, 5.4001e+01,
         6.0734e+01, 1.0227e+01],
        [3.2375e+01, 7.1729e+01, 3.4210e+01, 2.4976e+01, 3.0932e+00, 7.0406e+00,
         5.4712e+01, 4.2790e+01, 4.6682e+01, 8.0315e+01, 5.9237e+01, 9.3400e+01,
         2.2987e+01, 7.6110e+01, 4.9845e+01, 5.1739e+01, 7.7957e+01, 9.6511e+01,
         7.0791e+01, 1.0034e+02],
        [1.1414e+02, 7.3491e+00, 4.7253e+01, 1.2435e+02, 6.7357e+01, 5.9647e+01,
         3.7795e+01, 8.9134e+01, 1.4440e+01, 2.2720e+01, 1.2324e+02, 5.6057e+01,
       

In [102]:
# 7. Get the sum of each row in z2
torch.sum(z2, dim = 1)


tensor([ 203.0725,  703.1472, 1096.8367, 1193.2310, 1659.2432])

In [103]:
# 8. Get the mean of each column in z2
torch.mean(z2, dim = 0)

tensor([52.3343, 53.1363, 29.5641, 59.1508, 47.8096, 23.3346, 59.7400, 47.4276,
        39.1295, 48.3486, 53.4462, 44.8711, 19.2555, 66.7886, 44.8906, 57.8471,
        60.5548, 41.6658, 62.5650, 59.2462])

In [105]:
# 9. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(2, 2, 25)
# Print z3
print(z3)
print(z3.ndim)

tensor([[[1.5851e-01, 3.9695e+00, 5.9719e+00, 4.2746e+00, 9.0581e+00,
          8.3460e+00, 1.1623e+01, 1.0086e+01, 9.3240e+00, 8.9421e+00,
          2.0066e-01, 7.7218e+00, 1.3745e+01, 1.1339e+01, 1.3717e+01,
          1.7022e+01, 1.1573e+00, 2.8700e+01, 1.1142e+01, 2.6574e+01,
          3.8854e+01, 2.0087e+01, 1.7248e+01, 4.4198e+01, 4.6544e+01],
         [1.1155e+01, 3.3446e+01, 2.9376e+01, 4.6131e+01, 5.5394e+01,
          3.3476e+01, 5.1422e+01, 1.1036e+01, 3.1080e+01, 2.9747e+01,
          7.1180e+01, 7.8112e+00, 5.4001e+01, 6.0734e+01, 1.0227e+01,
          3.2375e+01, 7.1729e+01, 3.4210e+01, 2.4976e+01, 3.0932e+00,
          7.0406e+00, 5.4712e+01, 4.2790e+01, 4.6682e+01, 8.0315e+01]],

        [[5.9237e+01, 9.3400e+01, 2.2987e+01, 7.6110e+01, 4.9845e+01,
          5.1739e+01, 7.7957e+01, 9.6511e+01, 7.0791e+01, 1.0034e+02,
          1.1414e+02, 7.3491e+00, 4.7253e+01, 1.2435e+02, 6.7357e+01,
          5.9647e+01, 3.7795e+01, 8.9134e+01, 1.4440e+01, 2.2720e+01,
          1.2324